### ISSUE TITLE
S3 assets are broken

### ISSUE THREAD

**Issue by bricesanchez** [refinery/website#22]
Hi @parndt and @djones,

Do you have any idea why the S3 bucket is not working? 

Thanks,

Brice

**Comment by djones** [comment]
When I try to load an image seen in the blog, such as https://www.refinerycms.com/system/images/W1siZiIsIjIwMTcvMTAvMjYvMDIvMTEvMTgvMzY5NWRiN2QtYWI4ZC00YmQ5LThkYTctZWEwNTFmMGM5OGY3L3JlZmluZXJ5Y21zLXJlbGVhc2UtNC0wLTEuanBnIl0sWyJwIiwidGh1bWIiLCI4MTB4MzQwIl1d/refinerycms-release-4-0-1.jpg?sha=5fb2456f9be771ab

I see this error in Heroku:

```
2018-06-13T16:01:30.850664+00:00 app[web.1]: [fog][WARNING] 'mime-types' missing, please install and try again.
2018-06-13T16:01:30.850840+00:00 app[web.1]: 2018-06-13 16:01:30 +0000: Rack app error handling request { GET /system/images/W1siZiIsIjIwMTcvMTAvMjYvMDIvMTEvMTgvMzY5NWRiN2QtYWI4ZC00YmQ5LThkYTctZWEwNTFmMGM5OGY3L3JlZmluZXJ5Y21zLXJlbGVhc2UtNC0wLTEuanBnIl0sWyJwIiwidGh1bWIiLCI4MTB4MzQwIl1d/refinerycms-release-4-0-1.jpg }
2018-06-13T16:01:30.850844+00:00 app[web.1]: #<LoadError: cannot load such file -- mime/types>
2018-06-13T16:01:30.850847+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
2018-06-13T16:01:30.850855+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
2018-06-13T16:01:30.850857+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
2018-06-13T16:01:30.850859+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
2018-06-13T16:01:30.850862+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/storage.rb:11:in `rescue in new'
2018-06-13T16:01:30.850863+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/storage.rb:6:in `new'
2018-06-13T16:01:30.850866+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/dragonfly-s3_data_store-1.3.0/lib/dragonfly/s3_data_store.rb:85:in `storage'
2018-06-13T16:01:30.850868+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/dragonfly-s3_data_store-1.3.0/lib/dragonfly/s3_data_store.rb:50:in `block in read'
2018-06-13T16:01:30.850870+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/dragonfly-s3_data_store-1.3.0/lib/dragonfly/s3_data_store.rb:153:in `rescuing_socket_errors'
2018-06-13T16:01:30.850871+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/dragonfly-s3_data_store-1.3.0/lib/dragonfly/s3_data_store.rb:50:in `read'
```

I found the image here https://s3-us-west-1.amazonaws.com/refinerycms-website/2017/10/26/02/11/18/3695db7d-ab8d-4bd9-8da7-ea051f0c98f7/refinerycms-release-4-0-1.jpg

So I assume somewhere along the way through dragonfly or fog it's looking in the wrong place. Have there been any recent changes with those gems or anything else that comes to mind?

**Comment by bricesanchez** [comment]
Thanks @parndt and @djones !
